name: ble_integration_in_flutter_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
    sdk: ">=3.4.3 <4.0.0"

dependencies:
    flutter_blue_plus: ^1.34.4
    flutter_bloc: ^8.1.6
    equatable: ^2.0.5
    permission_handler: ^11.3.1
    path_provider: ^2.1.5
    flutter_spinkit: ^5.2.1

    flutter:
        sdk: flutter

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^3.0.0

flutter:
    uses-material-design: true
