name: ble_integration_in_flutter_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
    sdk: ">=3.4.3 <4.0.0"

dependencies:
    flutter_blue_plus: ^1.34.4
    geolocator: ^13.0.2
    flutter_bloc: ^8.1.6
    equatable: ^2.0.5
    permission_handler: ^11.3.1
    flutter_spinkit: ^5.2.1
    lottie: ^3.1.3

    flutter:
        sdk: flutter

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^3.0.0

flutter:
    uses-material-design: true

    assets:
        - assets/lottie/

    fonts:
        - family: EduAUVICWANTPre-SemiBold
          fonts:
              - asset: assets/fonts/EduAUVICWANTPre-SemiBold.ttf

        - family: HostGrotesk-SemiBold
          fonts:
              - asset: assets/fonts/HostGrotesk-SemiBold.ttf

        - family: HostGrotesk-Regular
          fonts:
              - asset: assets/fonts/HostGrotesk-Regular.ttf
